services:
  db:
    container_name: softwareengineering-database
    image: postgres
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./sql/tables.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dev_db"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    container_name: softwareengineering-backend
    build:
      context: ./src 
      dockerfile: Dockerfile.dev 
    environment:
      - HOKIDAR_USEPOLLING=true
    volumes:
      - ./src:/app
      - /app/node_modules
    ports:
      - "4444:4444/udp"

volumes:
  pgdata: {}
